# Device Configuration

# Device ID (각 VM에 맞게 수정)
device_id: "VM-A"  # VM-A, VM-B 등으로 변경

# MQTT Configuration
mqtt:
  host: "192.168.32.102"          # 로컬 개발: localhost, 멀티 VM: 192.168.1.100
  port: 1883                 # MQTT broker port
  topic: "devices/{device_id}/ingress"  # device_id에 따라 자동 생성
  qos: 1                     # MQTT QoS level
  keepalive: 60              # MQTT keepalive interval
  username: null             # MQTT username (optional)
  password: null             # MQTT password (optional)

# SignalR Configuration (선택사항)
# signalr:
#   url: "http://192.168.1.100:5000/hub"  # SignalR Hub IP
#   group: "{device_id}"                  # device_id에 따라 자동 생성
#   target: "ingress"

# Logging Configuration
logging:
  level: "INFO"              # Log level: DEBUG, INFO, WARNING, ERROR
  file: "device.log"         # Log file path
  max_size: 10485760         # Max log file size (10MB)
  backup_count: 5            # Number of backup files
