# IoT Data Bridge Main Configuration - MQTT Only

app_name: "IoT Data Bridge (MQTT)"
mapping_catalog_path: "config/mappings.yaml"
device_catalog_path: "config/devices.yaml"

# Input Layer Configuration - MQTT Only
input:
  type: "mqtt"
  mqtt:
    host: "0.0.0.0"          # 모든 인터페이스에서 접근 가능
    port: 1883
    username: null
    password: null
    topic: "iot/ingress"
    qos: 1
    keepalive: 60
    ssl: false

# Transports Layer Configuration - MQTT Only
transports:
  type: "mqtt"
  mqtt:
    host: "0.0.0.0"          # 모든 인터페이스에서 접근 가능
    port: 1883
    username: null
    password: null
    topic: "devices/{device_id}/ingress"  # Device별 토픽 (placeholder 사용)
    qos: 1
    keepalive: 60
    ssl: false

# Logging Configuration
logging:
  level: "INFO"
  file: "logs/iot_data_bridge_mqtt.log"
  max_size: 10485760  # 10MB
  backup_count: 5
  # Performance optimizations
  enable_async_logging: true
  log_batch_size: 100
  log_flush_interval: 1.0  # seconds
  enable_structured_logging: true
