# IoT Data Bridge Main Configuration
app_name: "IoT Data Bridge"
mapping_catalog_path: "middleware/config/mappings.yaml"
device_catalog_path: "middleware/config/devices.yaml"

# Input Layer Configuration
input:
  type: "mqtt"  # or "signalr"
  mqtt:
    host: "localhost"
    port: 1883
    username: null
    password: null
    topic: "iot/ingress"
    qos: 1
    keepalive: 60
    ssl: false
  signalr:
    url: "http://localhost:5000/hub"
    group: "iot_clients"
    username: null
    password: null

# Transports Layer Configuration
transports:
  type: "mqtt"  # or "signalr"
  mqtt:
    host: "localhost"
    port: 1883
    username: null
    password: null
    topic: "devices/{device_id}/ingress"
    qos: 1
    keepalive: 60
    ssl: false
  signalr:
    url: "http://localhost:5000/hub"
    group: "devices"
    username: null
    password: null

# Logging Configuration
logging:
  level: "INFO"
  file: "middleware/logs/iot_data_bridge.log"
  max_size: 10485760  # 10MB
  backup_count: 5
