# Mapping Catalog - Maps (equip_tag, message_id) to object and value_type
# Based on NMEA and marine equipment data specifications

mappings:
  # GPS Navigation Data
  - equip_tag: "GPS001"
    message_id: "GLL001"
    object: "GPS.Latitude"
    value_type: float
    
  - equip_tag: "GPS001"
    message_id: "GLL002"
    object: "GPS.Longitude"
    value_type: float
    
  - equip_tag: "GPS001"
    message_id: "VTG001"
    object: "GPS.CourseOverGround"
    value_type: float
    
  - equip_tag: "GPS001"
    message_id: "VTG002"
    object: "GPS.SpeedOverGround"
    value_type: float

  # Speed Log Data
  - equip_tag: "LOG001"
    message_id: "VHW003"
    object: "SpeedLog.SpeedThroughWater"
    value_type: float

  # Wind Data
  - equip_tag: "WIND001"
    message_id: "MWV101"
    object: "Wind.Angle"
    value_type: float
    
  - equip_tag: "WIND001"
    message_id: "MWV102"
    object: "Wind.Reference"
    value_type: text
    
  - equip_tag: "WIND001"
    message_id: "MWV103"
    object: "Wind.Speed"
    value_type: float
    
  - equip_tag: "WIND001"
    message_id: "MWV104"
    object: "Wind.SpeedUnit"
    value_type: text

  # Echo Sounder Data
  - equip_tag: "ES001"
    message_id: "DPT101"
    object: "EchoSounder.WaterDepth"
    value_type: float
    
  - equip_tag: "ES001"
    message_id: "MTW001"
    object: "EchoSounder.WaterTemperature"
    value_type: float

  # Engine 1 Data
  - equip_tag: "ENG001"
    message_id: "RPM001"
    object: "Engine1.DataSource"
    value_type: text
    
  - equip_tag: "ENG001"
    message_id: "RPM002"
    object: "Engine1.ShaftNumber"
    value_type: integer
    
  - equip_tag: "ENG001"
    message_id: "RPM003"
    object: "Engine1.Speed"
    value_type: float
    
  - equip_tag: "ENG001"
    message_id: "RPM004"
    object: "Engine1.PropellerPitch"
    value_type: float
    
  - equip_tag: "ENG001"
    message_id: "RPM005"
    object: "Engine1.Status"
    value_type: text

  # Engine 2 Data
  - equip_tag: "ENG002"
    message_id: "RPM006"
    object: "Engine2.DataSource"
    value_type: text
    
  - equip_tag: "ENG002"
    message_id: "RPM007"
    object: "Engine2.ShaftNumber"
    value_type: integer
    
  - equip_tag: "ENG002"
    message_id: "RPM008"
    object: "Engine2.Speed"
    value_type: float
    
  - equip_tag: "ENG002"
    message_id: "RPM009"
    object: "Engine2.PropellerPitch"
    value_type: float
    
  - equip_tag: "ENG002"
    message_id: "RPM010"
    object: "Engine2.Status"
    value_type: text

  # Rudder Data
  - equip_tag: "RUD001"
    message_id: "RSA001"
    object: "Rudder.StarboardAngle"
    value_type: float
    
  - equip_tag: "RUD001"
    message_id: "RSA002"
    object: "Rudder.StarboardStatus"
    value_type: text
    
  - equip_tag: "RUD001"
    message_id: "RSA003"
    object: "Rudder.PortAngle"
    value_type: float
    
  - equip_tag: "RUD001"
    message_id: "RSA004"
    object: "Rudder.PortStatus"
    value_type: text

  # VDR (Voyage Data Recorder) Data
  - equip_tag: "VDR001"
    message_id: "VDR001"
    object: "VDR.CurrentSet"
    value_type: float
    
  - equip_tag: "VDR001"
    message_id: "VDR002"
    object: "VDR.CurrentDrift"
    value_type: float

  # Inclinometer Data
  - equip_tag: "CLI001"
    message_id: "XDR001"
    object: "Inclinometer.Roll"
    value_type: float
    
  - equip_tag: "CLI001"
    message_id: "XDR002"
    object: "Inclinometer.Pitch"
    value_type: float

  # Gyrocompass Data
  - equip_tag: "GYRO001"
    message_id: "HDG001"
    object: "Gyrocompass.MagneticHeading"
    value_type: float
    
  - equip_tag: "GYRO001"
    message_id: "THS001"
    object: "Gyrocompass.TrueHeading"
    value_type: float

  # Diesel Engine 1 Data
  - equip_tag: "DE001"
    message_id: "Cy1ExhGasOutletTemp"
    object: "DieselEngine1.Cylinder1.ExhaustGasTemperature"
    value_type: float
    
  - equip_tag: "DE001"
    message_id: "Cy2ExhGasOutletTemp"
    object: "DieselEngine1.Cylinder2.ExhaustGasTemperature"
    value_type: float
    
  - equip_tag: "DE001"
    message_id: "Cy3ExhGasOutletTemp"
    object: "DieselEngine1.Cylinder3.ExhaustGasTemperature"
    value_type: float
    
  - equip_tag: "DE001"
    message_id: "Cy4ExhGasOutletTemp"
    object: "DieselEngine1.Cylinder4.ExhaustGasTemperature"
    value_type: float
    
  - equip_tag: "DE001"
    message_id: "Cy5ExhGasOutletTemp"
    object: "DieselEngine1.Cylinder5.ExhaustGasTemperature"
    value_type: float
    
  - equip_tag: "DE001"
    message_id: "Cy6ExhGasOutletTemp"
    object: "DieselEngine1.Cylinder6.ExhaustGasTemperature"
    value_type: float
    
  - equip_tag: "DE001"
    message_id: "Cy7ExhGasOutletTemp"
    object: "DieselEngine1.Cylinder7.ExhaustGasTemperature"
    value_type: float
    
  - equip_tag: "DE001"
    message_id: "Cy8ExhGasOutletTemp"
    object: "DieselEngine1.Cylinder8.ExhaustGasTemperature"
    value_type: float
    
  - equip_tag: "DE001"
    message_id: "Cy9ExhGasOutletTemp"
    object: "DieselEngine1.Cylinder9.ExhaustGasTemperature"
    value_type: float

  # Diesel Engine 1 Cylinder Pressure Data
  - equip_tag: "DE001"
    message_id: "Cyl1_Pmax"
    object: "DieselEngine1.Cylinder1.MaximumPressure"
    value_type: float
    
  - equip_tag: "DE001"
    message_id: "Cyl2_Pmax"
    object: "DieselEngine1.Cylinder2.MaximumPressure"
    value_type: float
    
  - equip_tag: "DE001"
    message_id: "Cyl3_Pmax"
    object: "DieselEngine1.Cylinder3.MaximumPressure"
    value_type: float
    
  - equip_tag: "DE001"
    message_id: "Cyl4_Pmax"
    object: "DieselEngine1.Cylinder4.MaximumPressure"
    value_type: float
    
  - equip_tag: "DE001"
    message_id: "Cyl5_Pmax"
    object: "DieselEngine1.Cylinder5.MaximumPressure"
    value_type: float
    
  - equip_tag: "DE001"
    message_id: "Cyl6_Pmax"
    object: "DieselEngine1.Cylinder6.MaximumPressure"
    value_type: float
    
  - equip_tag: "DE001"
    message_id: "Cyl7_Pmax"
    object: "DieselEngine1.Cylinder7.MaximumPressure"
    value_type: float
    
  - equip_tag: "DE001"
    message_id: "Cyl8_Pmax"
    object: "DieselEngine1.Cylinder8.MaximumPressure"
    value_type: float
    
  - equip_tag: "DE001"
    message_id: "Cyl9_Pmax"
    object: "DieselEngine1.Cylinder9.MaximumPressure"
    value_type: float

  # Diesel Engine 1 System Data
  - equip_tag: "DE001"
    message_id: "FGMassFlow"
    object: "DieselEngine1.FuelGasMassFlow"
    value_type: float
    
  - equip_tag: "DE001"
    message_id: "FOInletPress"
    object: "DieselEngine1.FuelOilInletPressure"
    value_type: float
    
  - equip_tag: "DE001"
    message_id: "FOInletTemp"
    object: "DieselEngine1.FuelOilInletTemperature"
    value_type: float
    
  - equip_tag: "DE001"
    message_id: "GE1_EXH_GAS_TEMP_TC_IN_H_AL"
    object: "DieselEngine1.ExhaustGasInletTemperatureAlarm"
    value_type: boolean
    
  - equip_tag: "DE001"
    message_id: "GE1_EXH_GAS_TEMP_TC_OUT_H_AL"
    object: "DieselEngine1.ExhaustGasOutletTemperatureAlarm"
    value_type: boolean
    
  - equip_tag: "DE001"
    message_id: "LOInletTemp"
    object: "DieselEngine1.LubricatingOilInletTemperature"
    value_type: float
    
  - equip_tag: "DE001"
    message_id: "Load"
    object: "DieselEngine1.Load"
    value_type: float
    
  - equip_tag: "DE001"
    message_id: "Power"
    object: "DieselEngine1.Power"
    value_type: float
    
  - equip_tag: "DE001"
    message_id: "RPM"
    object: "DieselEngine1.RPM"
    value_type: float
    
  - equip_tag: "DE001"
    message_id: "ScavPress"
    object: "DieselEngine1.ScavengePressure"
    value_type: float
    
  - equip_tag: "DE001"
    message_id: "ScavTemp"
    object: "DieselEngine1.ScavengeTemperature"
    value_type: float

  # Diesel Generator 1 & 2 Running Hours
  - equip_tag: "DG001"
    message_id: "RunhourHR"
    object: "DieselGenerator1.RunningHours"
    value_type: float
    
  - equip_tag: "DG002"
    message_id: "RunhourHR"
    object: "DieselGenerator2.RunningHours"
    value_type: float

  # Gas Engine 1 Data
  - equip_tag: "GE001"
    message_id: "ExhGasInletTempA"
    object: "GasEngine1.ExhaustGasInletTemperature"
    value_type: float
    
  - equip_tag: "GE001"
    message_id: "ExhGasOutletTemp"
    object: "GasEngine1.ExhaustGasOutletTemperature"
    value_type: float
    
  - equip_tag: "GE001"
    message_id: "LOInletPress"
    object: "GasEngine1.LubricatingOilInletPressure"
    value_type: float
    
  - equip_tag: "GE001"
    message_id: "RPM"
    object: "GasEngine1.RPM"
    value_type: float